# Generated by Django 5.2.3 on 2025-08-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('intern_code', models.CharField(max_length=200)),
                ('fabrication_code', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=50)),
                ('in_stock', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
