# Generated by Django 5.2.3 on 2025-08-31 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('related_problem', models.CharField(max_length=300)),
                ('diagnostic', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('open', 'Open'), ('running', 'Running'), ('finalized', 'Finalized'), ('canceled', 'canceled')], max_length=20)),
                ('enter_date', models.DateTimeField(auto_now_add=True)),
                ('exit_date', models.DateTimeField()),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='clients.client')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.vehicles')),
            ],
        ),
    ]
