# Generated by Django 5.2.3 on 2025-09-16 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0001_initial'),
        ('vehicles', '0003_remove_vehicles_client_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.vehicle'),
        ),
    ]
