# Generated by Django 5.2.3 on 2025-10-19 23:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('parts', '0002_part_delete_parts'),
        ('service_order', '0002_alter_serviceorder_vehicle'),
        ('vehicles', '0004_delete_vehicles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceorder',
            options={'ordering': ['-open_date']},
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='diagnostic',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='enter_date',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='exit_date',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='number',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='related_problem',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Close Date'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='description',
            field=models.TextField(default='', verbose_name='Problem description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='expected_finish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expected Finish Date'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Labor Cost'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observations'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='open_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='service_orders', to='parts.part'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('finished', 'finished')], default='Aberta', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Value'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='vehicles.vehicle'),
        ),
    ]
