# Generated by Django 5.2.3 on 2025-10-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0003_alter_serviceorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Problem description'),
        ),
    ]
