# Generated by Django 5.2.3 on 2025-09-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
