# Generated by Django 5.2.3 on 2025-09-16 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0002_alter_serviceorder_vehicle'),
        ('vehicles', '0003_remove_vehicles_client_vehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicles',
        ),
    ]
